name: Generate ASCII Artwork

on:
    push:

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            -   name: install cowsay program
                run: sudo apt-get install cowsay -y

            -   name: Execute cowsay command
                run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            -   name: Upload dragon text file
                uses: actions/upload-artifacts@v4
                with:
                    name: dragon-text-file
                    path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            -   name: download dragon text file
                uses: actions/download-artifact@v5
                with:
                    name: dragon-text-file

            -   name: Test file exists
                run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
            -   name: download dragon text file
                uses: actions/download-artifact@v5
                with:
                    name: dragon-text-file

            -   name: Display file
                run: cat dragon.txt

            -   name: Deploy
                run: echo "Deploying..."